### PR TITLE
Add additional appelate attachment page detection logic

### PR DESCRIPTION
**Pull request by ttys0dev**
Seems some appellate court attachment pages aren't getting detected so lets add a fallback.

### CODE REVIEW

**Comment by mlissner** [comment]
LGTM. Eduardo, will you merge if you think it's good?

**Comment by ERosendo** [comment]
@mlissner sure! @ttys0dev can you share an example of an attachment page that is not getting detected?

**Comment by ttys0dev** [comment]
> can you share an example of an attachment page that is not getting detected?

I think it was any attachment pages on ca10.

**Comment by ERosendo** [comment]
@ttys0dev thanks! I found one example. Here's the link:

https://ecf.ca10.uscourts.gov/n/beam/servlet/TransportRoom?servlet=ShowDoc/010010958402&caseId=87088&recapCaseNum=23-5097

We're using the form that is typically located at the bottom of the page to identify attachment pages. However, for documents exceeding a combined size of 30 MB, the form is not there.

image

**Review by ERosendo — APPROVED** [review]
The code looks good!

**Pull request merged**
