### PR TITLE
fix(background): use chrome.scripting.ExecutionWorld.MAIN for firefox compatibility

### PR DESCRIPTION
**Pull request by ttys0dev**
It seems firefox is picky here and won't accept the a `MAIN` string.

### CODE REVIEW

**Comment by ttys0dev** [comment]
rebased

**Comment by ttys0dev** [comment]
@ERosendo Does this look good to merge?

**Comment by mlissner** [comment]
@ttys0dev, what's the impact of this being wrong?

**Comment by ttys0dev** [comment]
> what's the impact of this being wrong?

I was seeing an exception being thrown.

**Comment by mlissner** [comment]
What version of FF?

**Comment by ttys0dev** [comment]
> What version of FF?

Was some ESR version I think where I saw the error, may have updated it since I tested though(currently on version 128 looks like).

**Pull request merged**
