### PR TITLE
Donation tab update

### PR DESCRIPTION
**Pull request by arcataroger**
Updated the donation tab per https://github.com/freelawproject/recap/issues/359

image

The link goes to https://donate.free.law/forms/supportflp

### CODE REVIEW

**Comment by mlissner** [comment]
Thanks, this is great! Can you also change the tab name to say "Donate" and make the button say "Donate to Free.law"?

**Comment by arcataroger** [comment]
> Thanks, this is great! Can you also change the tab name to say "Donate" and make the button say "Donate to Free.law"?

Sure, changed!

image

**Comment by mlissner** [comment]
I turned on the checks for you, and you got busted by the Release Notes bot. Can you add something, please?

**Comment by arcataroger** [comment]
Sure, I'll prep it as though it were a new version then (sorry, wasn't sure if you had another developer who normally did that). Give me a day or two :)

**Comment by ERosendo** [comment]
@mlissner This code looks good and I've updated the `CHANGES.md` file.

> did you want to try to roll several smaller fixes into one release?

@arcataroger We typically bundle minor fixes or updates into a single release.

**Pull request merged**
